Fix template string for viewing pool topics
In local development, controllers can return both "page" and "/page" to navigate to page.mustache. On dev, however, only "page" works, and the error message is a red herring that seems to be related to authlib interactions:

javax.servlet.ServletException: Cannot expose request attribute 'appVersion' because of an existing model object of the same name